FabriBLOG/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from FabriBLOG import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls', namespace = "fabriCua")),
    url(r'^admin/', include(admin.site.urls)),    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
                       url(r'^$', 'blog.views.verhome', name='Inicio' ),
                       url(r'^ver_post/(?P<id_post>[0-9]+)/$', 'blog.views.ver_post', name='vermipost'),
                       url(r'^cv/$', 'blog.views.vercv', name='CV' ),
                       url(r'^botonmagico/$', 'blog.views.verbtnmg', name='Boton Magico' ),
                       url(r'^calculadora/$', 'blog.views.vercal', name='Calculadora' ),
                       url(r'^contactos/$', 'blog.views.vercon', name='Contactos' ),
                       url(r'^conversor/$', 'blog.views.verconv', name='Conversor' ),
                       url(r'^cronometro/$', 'blog.views.vercro', name='Cronometro' ),
                       url(r'^galeria/$', 'blog.views.verimagen', name='Galeria' ),

                       url(r'^noticias/$', 'blog.views.vernoticias', name='Noticias' ),
                      )

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models




class Entrada(models.Model):
    class Meta:
        verbose_name = "Mi Entrada"
        verbose_name_plural = "Todas mis entradas"
        ordering=['-fecha']

    titulo = models.CharField(u'Titulo', max_length=100)
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    resumen= models.CharField(u'Resumen',max_length=512)
    contenido = models.TextField(u'Contenido')

    def __str__(self):
        return self.titulo


    

blog/views.py
from django.template import RequestContext
from django.shortcuts import render
from django.shortcuts import render_to_response, render, redirect
from blog.models import Entrada 

import os

def verhome(request):
    return render_to_response('Inicio.html',
                              {},
                              RequestContext(request))

def vercv(request):
    return render_to_response('CV.html',
                              {},
                              RequestContext(request))
# Create your views here.

def verbtnmg(request):
    return render_to_response('boton_magico.html',
                              {},
                              RequestContext(request))
# Create your views here.

def vercal(request):
    return render_to_response('Calculadora.html',
                              {},
                              RequestContext(request))
# Create your views here.

def vercon(request):
    return render_to_response('Contactos.html',
                              {},
                              RequestContext(request))
# Create your views here.

def verconv(request):
    return render_to_response('conversor.html',
                              {},
                              RequestContext(request))
# Create your views here.

def vercro(request):
    return render_to_response('cronometro.html',
                              {},
                              RequestContext(request))
# Create your views here.

def verimagen(request):
    return render_to_response('Image.html',{},RequestContext(request))

def vernoticias(request):
    context = RequestContext(request)
    posts = Entrada.objects.all()
    return render_to_response('noticias.html',{'posts':posts},context)

def ver_post(request, id_post):
    context = RequestContext(request)
    mi_post = Entrada.objects.get(id=id_post)
    return render_to_response('post.html',{'post':mi_post},context)

blog/templates/CV.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
    </head>
    <body class="red">

        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->

        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>

        
        <br></br>
    
        <div class="center-align">
            <IMG SRC="/static/img/john.jpg"><br>
                </div>
            <div class="center-align">
                <h3>INFORMACION PERSONAL</h3><br>
                Nombre:Fabrizio<br>
                Apellido:Cuassolo<br>
                Edad:16<br>
                Correo Elecetronico: fabricuassolo13@gmail.com<br>
                Direccion: Gustavo P Alvear 3456 Barrio Los Gigantes.
                <br>
                Telefono:3515234357<br>
                <br>
            </div>
           
    </body>
</html>
{% endblock %}

blog/templates/Calculadora.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="/static/css/materialize.css">
        <title>Inicio</title>
    </head> 
    <body class="red">
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->


        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>


        <br></br>

    <div class="container">
        <div style="text-align:center">

            <div class="row center" style="width:200px;"><input disabled value="0" id="display" style="text-align:center; margin-left:180%;" type="text" class="validate white-text"> <br></div>
            <a type="button" value="1" onclick="calcular(this)"class="waves-effect waves-light btn">1</a>
            <a type="button" value="2" onclick="calcular(this)"class="waves-effect waves-light btn">2</a>
            <a type="button" value="3" onclick="calcular(this)"class="waves-effect waves-light btn">3</a>
            <a type="button" value="+" onclick="calcular(this)"class="waves-effect waves-light btn">+</a><br>
            <a type="button" value="4" onclick="calcular(this)"class="waves-effect waves-light btn">4</a>
            <a type="button" value="5" onclick="calcular(this)"class="waves-effect waves-light btn">5</a>
            <a type="button" value="6" onclick="calcular(this)"class="waves-effect waves-light btn">6</a>
            <a type="button" value="-" onclick="calcular(this)"class="waves-effect waves-light btn">-</a><br>
            <a type="button" value="7" onclick="calcular(this)"class="waves-effect waves-light btn">7</a>
            <a type="button" value="8" onclick="calcular(this)"class="waves-effect waves-light btn">8</a>
            <a type="button" value="9" onclick="calcular(this)"class="waves-effect waves-light btn">9</a>
            <a type="button" value="*" onclick="calcular(this)"class="waves-effect waves-light btn">*</a><br>
            <a type="button" value="0" onclick="calcular(this)"class="waves-effect waves-light btn">0</a>
            <a type="button" value="/" onclick="calcular(this)"class="waves-effect waves-light btn">/</a>
            <a type="button" value="=" onclick="calcular(this)"class="waves-effect waves-light btn">=</a>
            <a type="button" value="CE" onclick="calcular(this)"class="waves-effect waves-light btn">CE</a><br>

        </div>
    </div>

    <br></br>


</body>
</html>
<script>

    function calcular(boton){

        var btn = boton.getAttribute("value");
        console.log(btn);
        var display = document.getElementById("display");

        if(display.value=="0"){
            display.value="";
        }

        if(btn=="="){
            resultado=eval(display.value); 
            display.value=resultado;
        }else{
            if(btn=="CE"){
                display.value=0;
            }else{
                display.value=display.value+btn;
            }
        }
    }

</script>
{% endblock %}

blog/templates/Contactos.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
    </head>
    <body class="red">
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->


        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>


        
        <br></br>
    
        <div class="container">
            <form>
                Nombre:<br>
                <input type="text" name="Nombre"></input><br>
            Apellido:<br>
            <input type="text" name="Apellido"></input><br>
        Email:<br>
        <input type="text" name="Email"></input><br>
    Asunto:<br>
    <input type="text" name="Asunto"></input><br>
Mensaje:<br>
<input type="text" name="Mensaje"></input><br>
<div class="center-align">
    <a type="submit" value="Enviar" class="waves-effect waves-light btn">Enviar</a>
</div>
</form>
</div>

<br></br>


</body>
</html>
{% endblock %}

blog/templates/Image.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
    </head>
    <body onload="cambiar()" class="red">

        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->

        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>


        
            </div>
        </nav>


        <div class="content" align="center">
            <h3>Galeria de Imagenes</h3>
            <progress id="barra" max="100" value="0"></progress><br><br>
            <img id="img" height = "400px" width="600px" src="/static/img/1.jpg"/>

            <br></br>
        <br></br>

    </div>


</body>
</html>

<script>
    var images = ["/static/img/1.jpg","/static/img/2.jpg","/static/img/3.jpg","/static/img/4.jpg"];
    var tiempo = setInterval(function(){load();},1000);

    $(document).ready(function(){
        load();
    });

    var barra = document.getElementById("barra");
    var img = document.getElementById("img");
    a = 0;
    i = 1;
    var time = setInterval(load, 200);

    function load(){
        a +=5 ;
        barra.value = a;
        if (barra.value == 100){
            a=0;
            barra.value = a;
            img.setAttribute("src",images[i]);
            i++;
            if(i==4){i=0}
        }
    }
</script>
{% endblock %}

blog/templates/Inicio.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}


<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="/static/css/materialize.css">
        <div class="center-align">
            <body class="red">

                <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
                <script type="text/javascript" src="js/materialize.js"></script>

                <h2>¿Que es River Plate?</h2><br>
                <IMG SRC="/static/img/river.jpg"><br>
                    <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p><br>

                    </div>
            
{% endblock %}

blog/templates/base.html
{% load staticfiles %}
<html>	
    <head>

        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>FabriBlog</title>
    </head>

    <body class="red">

        <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="{% url 'fabriCua:Inicio' %}">Inicio</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Galeria' %}">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Cronometro' %}">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Conversor' %}">Conversor</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Boton Magico' %}">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Calculadora' %}">Calculadora</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'fabriCua:Noticias' %}">Noticias</a></li>           
            

        </ul>


        <nav class="grey darken-4">
            <div class="nav-wrapper" >
                <a href="#!" class="brand-logo">FabriBLOG</a>
                <ul class="right hide-on-med-and-down">
                    
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>

                    <li><a href="{% url 'fabriCua:CV' %}">Curriculum</a></li>
                    
                    <li><a href="{% url 'fabriCua:Contactos' %}">Contactos</a></li>

                    <li><a href="{% url 'fabriCua:Noticias' %}">Noticias</a></li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Programas<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
                </ul>
            </div>
        </nav>
        
         {% block contenido %}
        {% endblock %}

        
        <footer class="footer">
            <div class="grey darken-4">
                <div class="container">
                    <div class="row">
                        <div class="col l6 s12">
                            <h5 class="white-text">FabriBLOG</h5>
                            <p class="grey-text text-lighten-4">Este blog fue hecho por Fabrizio Cuassolo para la realizacion de un proyecto escolar</p>
                        </div>
                        <div class="col l4 offset-l2 s12">
                            <h5 class="white-text">Encuentrame en:</h5>
                            <ul>
                                <li><a class="grey-text text-lighten-3" href="https://plus.google.com/?hl=es">Google+</a></li>
                                <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/?_rdr">Facebook</a></li>
                                <li><a class="grey-text text-lighten-3" href="https://twitter.com/?lang=es">Twitter</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="footer-copyright">

                </div>
            </div>
        </footer>
        
       

    </body>
</html>

blog/templates/boton_magico.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="css/style.css">
    <head>
        <h1>CONEXION FALLIDA VUELVA MAS TARDE..</h1>
    </head>
    <body>
        <div class="boton_magico">
            <input type="button"  id="magico" value="Continuar" onmouseover="troll()" onclick="win()" ></input>
        </div>
    </body>

</html>
<script>
    function troll(){
        document.getElementById("magico").style.marginTop = Math.floor((Math.random()*400) + 1);
        document.getElementById("magico").style.marginLeft = Math.floor((Math.random()*400) + 1);
    }
    function win(){
        alert("¡Ganaste!");
        location.href="Inicio.html";
    }
</script>
{% endblock %}

blog/templates/conversor.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}

<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="materialize/css/materialize.css">
        <title>Inicio</title>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
    </head>
    <body class="red">
        <ul id='dropdown1' class='dropdown-content'>

            <li><a href="Image.html">Galeria</a></li>
            <li class="divider"></li>
            <li><a href="cronometro.html">Cronometro</a></li>
            <li class="divider"></li>
            <li><a href="conversor.html">Conversor de Moneda</a></li>
            <li class="divider"></li>
            <li><a href="boton_magico.html">Boton Troll</a></li>
            <li class="divider"></li>
            <li><a href="Calculadora.html">Calculadora</a></li>

        </ul>
        
        
        <br></br>
        
        <div class="container">



            <div>
                De<select id="tipoMoneda" class="col l5 offset-l1"> 
                <option selected>Seleccionar Tipo de Moneda</option>
                <option value="1">Pesos Argentinos </option> 
                <option value="2">Dolares </option> 
                <option value="3">Euros </option> 
                <option value="4">Pesos Uruguayos</option>
                <option value="5">Pesos Chilenos</option></select>
                <input type="text" id="valor" value=""></input>
        </div>
        <div>
            De<select id="TipoMonedaFinal"> 
            <option selected>Seleccionar Tipo de Moneda</option>
            <option value="1">Pesos Argentinos </option> 
            <option value="2">Dolares </option> 
            <option value="3">Euros </option> 
            <option value="4">Pesos Uruguayos</option>
            <option value="5">Pesos Chilenos</option></select>
            <input type="text" id="valorFinal" value=""></input>
        </div>

    <div class="center-align">
        <a type="button" id="botonConvertir" value="Convertir" onclick="cambio()" class="waves-effect waves-light btn">Convertir</a> 
        <a type="button" id="botonLimpiar" value="Limpiar" onclick="limpieza()" class="waves-effect waves-light btn">Limpiar</a>
    </div>
    </div>


<br></br>

</body>
<script>
    function limpieza(){
        document.getElementById("valorFinal").value = "";
        document.getElementById("valor").value = "";
    }
    function cambio(){
        var seleccion1 = document.getElementById("tipoMoneda");
        var valorSeleccion1 =seleccion1.options[seleccion1.selectedIndex].value;

        var seleccion2 = document.getElementById("TipoMonedaFinal"); 
        var valorSeleccion2 = seleccion2.options[seleccion2.selectedIndex].value;
        console.log(valorSeleccion1);
        console.log(valorSeleccion2);
        var valorDivisa=0.0;

        switch(parseInt(valorSeleccion1)) {
            case 1:

                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=1;
                        break;
                    case 2:
                        valorDivisa=0.11231;
                        break;
                    case 3:
                        valorDivisa=0.10396;
                        break;    
                    case 4:
                        valorDivisa=68.540;
                        break;
                    case 5:
                        valorDivisa=2.9911;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 2:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        console.log("enter");
                        valorDivisa=8.8968;
                        break;
                    case 2:
                        valorDivisa=1.0;
                        break;
                    case 3:
                        valorDivisa=0.92687;
                        break;    
                    case 4:
                        valorDivisa=609.79;
                        break;
                    case 5:
                        valorDivisa=26.611;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 3:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=9.5988;
                        break;
                    case 2:
                        valorDivisa=1,0755;
                        break;
                    case 3:
                        valorDivisa=1;
                        break;    
                    case 4:
                        valorDivisa=657.90;
                        break;
                    case 5:
                        valorDivisa=28.711;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;    
            case 4:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.014590;
                        break;
                    case 2:
                        valorDivisa=0.0016400;
                        break;
                    case 3:
                        valorDivisa=0.0015200;
                        break;    
                    case 4:
                        valorDivisa=1;
                        break;
                    case 5:
                        valorDivisa=0.043640;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 5:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.33433;
                        break;
                    case 2:
                        valorDivisa=0.037580; 
                        break;
                    case 3:
                        valorDivisa=0.034830;
                        break;    
                    case 4:
                        valorDivisa=22.915;
                        break;
                    case 5:
                        valorDivisa=1;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 0:
                alert("Debe Seleccionar una Divisa");
                break;
        }
        var moneda = document.getElementById("valor");
        var resultado = eval(parseFloat(moneda.value)*parseFloat(valorDivisa));
        var MostrarResultado = document.getElementById("valorFinal");
        MostrarResultado.value=resultado;
        console.log(moneda.value+" * "+ valorDivisa+" = "+resultado);
    }
    $(document).ready(function(){
        $("select").material_select()
    });
</script>

{% endblock %}

</html>

blog/templates/noticias.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block contenido %}


<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="/static/css/materialize.css">
        <div class="center-align">
            </head>
        <body class="red">

            {% for post in posts %}
            <div class="post-preview">
                <a href="{% url 'fabriCua:vermipost' post.id %}">
                    <h2 class="post-title">
                        {{post.titulo}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{post.resumen}}
                    </h3>
                </a>
            </div>
            <hr>
            {% endfor %}

            <script type="text/javascript" src="js/jquery-1.11.3.js"></script>
            <script type="text/javascript" src="js/materialize.js"></script>
        </body>



        {% endblock %}  

blog/templates/post.html
{% extends 'base.html' %}

{% block contenido %}


<article>
    <div class="container">     
                <h2 class="section-heading">{{post.titulo}}</h2>
                <h3 class="section-heading">{{post.fecha}}</h3>

                <p>{{post.contenido}}</p>



            
    </div>
</article>



{% endblock %} 